### ISSUE TITLE
unite_llm does not run

### ISSUE THREAD

**Issue by nickworks** [freckletonj/uniteai#29]
Hello, after installing with `pip3 install --user "uniteai[all]"` I try to run `uniteai_llm`, but receive the following error:

```
Traceback (most recent call last):
  File "/Users/nick/.local/bin/uniteai_llm", line 5, in <module>
    from uniteai.llm_server import main
  File "/Users/nick/.local/lib/python3.11/site-packages/uniteai/llm_server.py", line 99, in <module>
    args = config['local_llm']
           ~~~~~~^^^^^^^^^^^^^
TypeError: 'NoneType' object is not subscriptable
```

Is there something I'm doing wrong? Thanks!

Mac OS X 14.1.1
/Users/nick/.local/bin/uniteai_llm
/Users/nick/.local/bin/uniteai_lsp

**Comment by freckletonj** [comment]
For some reason it sounds like you don't have a `uniteai.yml` file.

If you have added `uniteai` to your editor, upon first running it should create this file and ask you to restart your editor. I'm still trying to make this process smoother, so thanks for the bug report.

The file is copied from: https://github.com/freckletonj/uniteai/blob/master/uniteai/.uniteai.yml.example#L95

And the LSP looks in these locations for it, in this order:

```python
    './.uniteai.yml',
    './.uniteai.yaml',
    os.path.expanduser('~/.uniteai.yml'),
    os.path.expanduser('~/.uniteai.yaml'),
```
So, I'd say try running it in the editor first, and allowing it to create the file for you.

Or copy it to one of those locations.

**Comment by freckletonj** [comment]
It looks like it's trying to create that log file, but your system is read-only:

```
OSError: [Errno 30] Read-only file system: '/log_file.log'
```

Is your file system read-only? Or, I can't quite tell, it might be trying to make that file at root `/`, which I have no idea why it would default there.

Here's the relevant line of code: https://github.com/freckletonj/uniteai/blob/master/uniteai/lsp_server.py#L70

Oh, are you running `lsp_server` from your root directory? That's where it's trying to put the file. Try going into some user directory where it will have permissions to create it.

I'm happy to help you keep debugging if that doesn't work. It helps me to robustify this!

**Comment by hrehfeld** [comment]
> For some reason it sounds like you don't have a `uniteai.yml` file.
> 
> If you have added `uniteai` to your editor, upon first running it should create this file and ask you to restart your editor. I'm still trying to make this process smoother, so thanks for the bug report.
> 
> The file is copied from: https://github.com/freckletonj/uniteai/blob/master/uniteai/.uniteai.yml.example#L95
> 
> And the LSP looks in these locations for it, in this order:
> 
> ```python
>     './.uniteai.yml',
>     './.uniteai.yaml',
>     os.path.expanduser('~/.uniteai.yml'),
>     os.path.expanduser('~/.uniteai.yaml'),
> ```
> 
> So, I'd say try running it in the editor first, and allowing it to create the file for you.
> 
> Or copy it to one of those locations.

When installing in a venv, this file is also missing. (and the emacs setup doesn't seem to have code to create it)
